version: '2'
services:
  db:
    image: "postgres:9.4"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    expose:
      - 5432
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test_db
  web:
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
     - "4444:80"
    volumes:
     - .:/app
    links: 
      - db
    environment:
      - FLASK_APP=FlaskBasicAppWithConfig.py
      - FLASK_DEBUG=1
      - SECRET_KEY=abcdef
    command: flask run --host=0.0.0.0 --port=80